### ISSUE TITLE
Перенести урок по массивам

### ISSUE THREAD

**Issue by fey** [hexlet-basics/exercises-clang#12]
https://ru.hexlet.io/courses/introduction_to_c/lessons/arrays_in_c/theory_unit

**Comment by usernaimandrey** [comment]
Привет. Описание к уроку текстом или как в других уроках видео вставить, и есть ли ссылка на видео?

**Comment by fey** [comment]
Публичной ссылки на вставку видео нет, есть вот такая. Должна сработать на код бейзиксе
```
<div style="padding:62.5% 0 0 0;position:relative;"><iframe src="https://player.vimeo.com/video/129983970?h=a3b1f99ad2&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479" frameborder="0" allow="autoplay; fullscreen; picture-in-picture" allowfullscreen style="position:absolute;top:0;left:0;width:100%;height:100%;" title="Arrays in C"></iframe></div><script src="https://player.vimeo.com/api/player.js"></script>
```

**Comment by fey** [comment]
Просто видео, по аналогии с другими уроками.

**Comment by usernaimandrey** [comment]
> Просто видео, по аналогии с другими уроками.

Понял, спасибо,  возьму в работу

**Comment by usernaimandrey** [comment]
https://github.com/hexlet-basics/exercises-clang/pulls
